version: '3.9'
services:

    prometheus:
      image: prom/prometheus
      container_name: prometheus
      ports:
         - 9090:9090
    #  volumes:
     #     - ./C://Users/kiryx/IdeaProjects/Examenator/prometheus.yml

    grafana:
      image: grafana/grafana:9.3.0
      ports:
        - 3000:3000
