global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus_plus'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.56.1:8085']


